In [ ]:
import pandas as pd

In [ ]:
atletas_120 = pd.read_csv('athlete_events.csv')
atletas_120=atletas_120.loc[atletas_120["Season"] != 'Winter']
atletas_120=atletas_120.reset_index(drop=True) 
atletas_120["Id"] = atletas_120.index

display(atletas_120)

            ID                                Name  ... Medal      Id
0            1                           A Dijiang  ...   NaN       0
1            2                            A Lamusi  ...   NaN       1
2            3                 Gunnar Nielsen Aaby  ...   NaN       2
3            4                Edgar Lindenau Aabye  ...  Gold       3
4            8  Cornelia "Cor" Aalten (-Strannood)  ...   NaN       4
...        ...                                 ...  ...   ...     ...
222547  135565            Fernando scar Zylberberg  ...   NaN  222547
222548  135566          James Francis "Jim" Zylker  ...   NaN  222548
222549  135567        Aleksandr Viktorovich Zyuzin  ...   NaN  222549
222550  135567        Aleksandr Viktorovich Zyuzin  ...   NaN  222550
222551  135568              Olga Igorevna Zyuzkova  ...   NaN  222551

[222552 rows x 16 columns]

##Tabela 1 - Edição dos Jogos

In [ ]:
edicaoDosJogos=pd.DataFrame(data=atletas_120[['Year', 'City']])
edicaoDosJogos=edicaoDosJogos.drop_duplicates("Year")
edicaoDosJogos=edicaoDosJogos.sort_values(by=["Year"])
edicaoDosJogos = edicaoDosJogos.reset_index(drop=True) #Reseta os index da tabela
edicaoDosJogos = edicaoDosJogos.rename({"Year":"Ano"}, axis=1)
edicaoDosJogos = edicaoDosJogos.rename({"City":"Cidade"}, axis=1)
edicaoDosJogos["NumerodaEdicao"]=None
edicaoDosJogos["TotaldeAtletas"] = None

for i in range(len(edicaoDosJogos.index)):
  edicaoDosJogos.at[i, 'NumerodaEdicao']=1+i

edicaoDosJogos["Mascote"]=['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'Waldi', 'Amik', 'Misha', 'Sam', 'Hodori', 'Cobi', 'Izzy', 'Olly, Syd e Millie','Athena e Phevos','Beibei, Jingjing, Huanhuan, Yingying e Nini','Wenlock','Vinícius']

In [ ]:
# Função que ajuda a encontrar a qtd de atletas
def setNumeroDeAtletas (row):
  atletasDeUmAno=pd.DataFrame(data=atletas_120[['Year', 'Name']])
  atletasDeUmAno=atletasDeUmAno.loc[atletasDeUmAno["Year"] ==row.Ano]
  atletasDeUmAno=atletasDeUmAno.drop_duplicates("Name")
  row.TotaldeAtletas=len(atletasDeUmAno.index)
  return row

edicaoDosJogos = edicaoDosJogos.apply(lambda x: setNumeroDeAtletas(x),axis=1)
anos = edicaoDosJogos['Ano'].tolist()

In [ ]:
edicaoDosJogos=edicaoDosJogos.fillna("-")
display(edicaoDosJogos)

     Ano  ...                                      Mascote
0   1896  ...                                            -
1   1900  ...                                            -
2   1904  ...                                            -
3   1906  ...                                            -
4   1908  ...                                            -
5   1912  ...                                            -
6   1920  ...                                            -
7   1924  ...                                            -
8   1928  ...                                            -
9   1932  ...                                            -
10  1936  ...                                            -
11  1948  ...                                            -
12  1952  ...                                            -
13  1956  ...                                            -
14  1960  ...                                            -
15  1964  ...                                            -
16  1968  ...                                            -
17  1972  ...                                        Waldi
18  1976  ...                                         Amik
19  1980  ...                                        Misha
20  1984  ...                                          Sam
21  1988  ...                                       Hodori
22  1992  ...                                         Cobi
23  1996  ...                                         Izzy
24  2000  ...                           Olly, Syd e Millie
25  2004  ...                              Athena e Phevos
26  2008  ...  Beibei, Jingjing, Huanhuan, Yingying e Nini
27  2012  ...                                      Wenlock
28  2016  ...                                     Vinícius

[29 rows x 5 columns]

In [ ]:
edicaoDosJogos.to_csv("edicoes.csv")

##Tabela 2 - Atleta

In [ ]:
atleta = pd.DataFrame(data=atletas_120[['Name', 'Sex','Age', 'Year']])
atleta = atleta.drop_duplicates("Name")
atleta = atleta.sort_values(by=["Name"])

atleta = atleta.rename({"Name":"Nome"}, axis=1)
atleta = atleta.rename({"Sex":"Sexo"}, axis=1)
atleta = atleta.rename({"Age":"AnoDeNascimento"}, axis=1)

atleta["AnoDeNascimento"]=atleta["Year"]-atleta["AnoDeNascimento"]
#atleta["AnoDeNascimento"]= atleta["AnoDeNascimento"].astype(str)

atleta=atleta.drop(columns=['Year'])
atleta = atleta.reset_index(drop=True) #Reseta os index da tabela
atleta["Id"] = atleta.index
atleta = atleta.reindex(columns=["Id","Nome","AnoDeNascimento","Sexo"])

In [ ]:
atleta=atleta.fillna("-")
atleta.head(50)

    Id                                       Nome AnoDeNascimento Sexo
0    0    Gabrielle Marie "Gabby" Adcock (White-)            1991    F
1    1        Eleonora Margarida Josephina Scmitt            1932    F
2    2                            Jean Hauptmanns            1886    M
3    3    Luis ngel Fernando de los Santos Grossi            1925    M
4    4                                     Th Anh            1996    F
5    5                                Th Ngn Thng            1989    F
6    6                                    Tin Tun            1967    M
7    7                                  A Dijiang            1968    M
8    8                                   A Lamusi            1989    M
9    9                   A. Aanantha Sambu Mayavo            1966    M
10  10                            A. Abdul Razzak               -    M
11  11                                  A. Albert               -    M
12  12                                    A. Brun               -    F
13  13                                 A. Buydens               -    M
14  14                             A. Charles Six               -    M
15  15                               A. Christory               -    M
16  16                                  A. Darnis               -    M
17  17                                  A. Dubois               -    M
18  18                              A. Duponcheel               -    M
19  19                                 A. E. Page               -    M
20  20                              A. G. Chagale               -    M
21  21             A. Germaine Golding (Regnier-)               -    F
22  22                                 A. Godinat               -    M
23  23                          A. Hurtado Vargas               -    M
24  24                           A. Hussain Ahmed               -    M
25  25                             A. J. J. Fridt               -    M
26  26    A. J. Tyronne Benildus "Benny" Fernando            1969    M
27  27                      A. Joshua "Josh" West            1977    M
28  28                                A. Kordonis               -    M
29  29                                  A. Laffen               -    M
30  30                              A. Lafontaine               -    M
31  31                          A. Lambrecht, Jr.               -    M
32  32                                   A. Lawry               -    M
33  33                                A. M. Woods               -    M
34  34                               A. O. Pinner               -    M
35  35                               A. Papadakis               -    M
36  36                                 A. Porcher               -    M
37  37                                 A. Priftis               -    M
38  38                                A. R. Upton               -    M
39  39                                   A. Roger               -    M
40  40                               A. S. Harley               -    M
41  41                          A. Sattar Basheer               -    M
42  42                                 A. Schmitt               -    M
43  43                            A. Tark Erilmez               -    M
44  44                     A. Tryfiatis-Trypiapis               -    M
45  45                                 A. V. Ford               -    M
46  46                      A. W. Nancy "Nan" Rae            1944    F
47  47                               A. Willcocks               -    M
48  48                            A. Wynne Rogers               -    M
49  49                              A. de Romigny               -    M

In [ ]:
atleta.to_csv('atletas.csv')

##Tabela 3 - Comitê Olímpico

In [ ]:
#Esse comando foi só pra criar uma nova tabela com base na coluna de outra
comiteOlimpico = pd.DataFrame(data=atletas_120[['NOC', 'Team']])
comiteOlimpico = comiteOlimpico.drop_duplicates() #Remove linhas duplicadas
comiteOlimpico = comiteOlimpico.sort_values("NOC") #Ordena pela coluna 'NOC"
comiteOlimpico = comiteOlimpico.reset_index(drop=True) #Reseta os index da tabela
comiteOlimpico = comiteOlimpico.rename({"NOC":"Id"}, axis=1)
comiteOlimpico = comiteOlimpico.rename({"Team":"País"}, axis=1)
#comiteOlimpico = comiteOlimpico.drop_duplicates(['Id']) #Remove linhas duplicadas
comiteOlimpico = comiteOlimpico.reindex(columns=["Id","País"])

In [ ]:
comiteOlimpico=comiteOlimpico.fillna("-")
comiteOlimpico.head(15)

     Id                  País
0   AFG           Afghanistan
1   AHO  Netherlands Antilles
2   ALB               Albania
3   ALG               Algeria
4   AND               Andorra
5   ANG                Angola
6   ANT   Antigua and Barbuda
7   ANZ    Sydney Rowing Club
8   ANZ           Australasia
9   ARG               Antares
10  ARG           Argentina-1
11  ARG               Acturus
12  ARG           Argentina-2
13  ARG                 Mizar
14  ARG                 Tango

In [ ]:
#comiteOlimpico.to_csv("comitesComRepeticao.csv")

In [ ]:
#Substituindo pelos países do Wikipedia
IOC = pd.read_csv('IOC - Países.csv')
IOC=pd.DataFrame(data=IOC[['NOC','País']])
IOC = IOC.rename({"NOC":"Id"}, axis=1)
IOC = IOC.sort_values("Id") #Ordena pela coluna 'NOC"
IOC = IOC.reset_index(drop=True) 

comiteOlimpico=IOC
comiteOlimpico=comiteOlimpico.fillna("-")
display(comiteOlimpico)

      Id                  País
0    AFG           Afghanistan
1    AHO  Netherlands Antilles
2    ALB               Albania
3    ALG               Algeria
4    AND               Andorra
..   ...                   ...
225  YEM                 Yemen
226  YMD           South Yemen
227  YUG            Yugoslavia
228  ZAM                Zambia
229  ZIM              Zimbabwe

[230 rows x 2 columns]

In [ ]:
comiteOlimpico.to_csv("comites.csv")

##Tabela 4 - Esporte/Modalidade

In [ ]:
esporteModalidade1 = pd.DataFrame(data=atletas_120[['Event', 'Sport']])
esporteModalidade1 = esporteModalidade1.drop_duplicates()
esporteModalidade1 = esporteModalidade1.sort_values("Event")
esporteModalidade1 = esporteModalidade1.reset_index(drop=True)
esporteModalidade1 = esporteModalidade1.rename({"Event":"Nome"}, axis=1)
esporteModalidade1 = esporteModalidade1.rename({"Sport":"EsportePai"}, axis=1)

esporteModalidade2 = pd.DataFrame(data=atletas_120[['Sport']])
esporteModalidade2 = esporteModalidade2.rename({"Sport":"Nome"}, axis=1)
esporteModalidade2 = esporteModalidade2.drop_duplicates()
esporteModalidade2["EsportePai"]=None
esporteModalidade2 = esporteModalidade2.sort_values("Nome")
esporteModalidade2 = esporteModalidade2.reset_index(drop=True)

esporteModalidade = pd.concat([esporteModalidade1, esporteModalidade2])
esporteModalidade = esporteModalidade.sort_values("Nome")
esporteModalidade = esporteModalidade.reset_index(drop=True)
esporteModalidade["Id"] = esporteModalidade.index
esporteModalidade= esporteModalidade.reindex(columns=["Id","Nome", "EsportePai"])

In [ ]:
esporteModalidade=esporteModalidade.fillna("-")
esporteModalidade.head(50)

    Id                                               Nome        EsportePai
0    0                                        Aeronautics                 -
1    1                      Aeronautics Mixed Aeronautics       Aeronautics
2    2                                           Alpinism                 -
3    3                            Alpinism Mixed Alpinism          Alpinism
4    4                                            Archery                 -
5    5               Archery Men's Au Chapelet, 33 metres           Archery
6    6               Archery Men's Au Chapelet, 50 metres           Archery
7    7            Archery Men's Au Cordon Dore, 33 metres           Archery
8    8            Archery Men's Au Cordon Dore, 50 metres           Archery
9    9                 Archery Men's Championnat Du Monde           Archery
10  10                    Archery Men's Continental Style           Archery
11  11                Archery Men's Double American Round           Archery
12  12                    Archery Men's Double York Round           Archery
13  13                           Archery Men's Individual           Archery
14  14  Archery Men's Pole Archery, Large Birds, Indiv...           Archery
15  15      Archery Men's Pole Archery, Large Birds, Team           Archery
16  16  Archery Men's Pole Archery, Small Birds, Indiv...           Archery
17  17      Archery Men's Pole Archery, Small Birds, Team           Archery
18  18             Archery Men's Sur La Perche a La Herse           Archery
19  19          Archery Men's Sur La Perche a La Pyramide           Archery
20  20  Archery Men's Target Archery, 28 metres, Indiv...           Archery
21  21      Archery Men's Target Archery, 28 metres, Team           Archery
22  22  Archery Men's Target Archery, 33 metres, Indiv...           Archery
23  23      Archery Men's Target Archery, 33 metres, Team           Archery
24  24  Archery Men's Target Archery, 50 metres, Indiv...           Archery
25  25      Archery Men's Target Archery, 50 metres, Team           Archery
26  26                                 Archery Men's Team           Archery
27  27                           Archery Men's Team Round           Archery
28  28                        Archery Men's Unknown Event           Archery
29  29              Archery Women's Double Columbia Round           Archery
30  30              Archery Women's Double National Round           Archery
31  31                         Archery Women's Individual           Archery
32  32                               Archery Women's Team           Archery
33  33                         Archery Women's Team Round           Archery
34  34                                   Art Competitions                 -
35  35                Art Competitions Mixed Architecture  Art Competitions
36  36  Art Competitions Mixed Architecture, Architect...  Art Competitions
37  37  Art Competitions Mixed Architecture, Designs F...  Art Competitions
38  38  Art Competitions Mixed Architecture, Unknown E...  Art Competitions
39  39                  Art Competitions Mixed Literature  Art Competitions
40  40  Art Competitions Mixed Literature, Dramatic Works  Art Competitions
41  41      Art Competitions Mixed Literature, Epic Works  Art Competitions
42  42     Art Competitions Mixed Literature, Lyric Works  Art Competitions
43  43   Art Competitions Mixed Literature, Unknown Event  Art Competitions
44  44                       Art Competitions Mixed Music  Art Competitions
45  45  Art Competitions Mixed Music, Compositions For...  Art Competitions
46  46  Art Competitions Mixed Music, Compositions For...  Art Competitions
47  47  Art Competitions Mixed Music, Instrumental And...  Art Competitions
48  48        Art Competitions Mixed Music, Unknown Event  Art Competitions
49  49               Art Competitions Mixed Music, Vocals  Art Competitions

In [ ]:
esporteModalidade.to_csv("esportes.csv")

##Tabela 5 - Participação Comitês

In [ ]:
participacaoComites=pd.DataFrame(data=atletas_120[['Year', 'NOC']])
participacaoComites=participacaoComites.drop_duplicates(['Year', 'NOC'])
participacaoComites=participacaoComites.sort_values(by=['NOC','Year'])
participacaoComites=participacaoComites.reset_index(drop=True) #Reseta os index da tabela
participacaoComites=participacaoComites.rename({"Year":"AnoEdicao"}, axis=1)
participacaoComites=participacaoComites.rename({"City":"Cidade"}, axis=1)
participacaoComites=participacaoComites.rename({"NOC":"IdComite"}, axis=1)

participacaoComites["QtdAtletas"]=None
participacaoComites["QtdOuro"] = None
participacaoComites["QtdPrata"]=None
participacaoComites["QtdBronze"]=None
participacaoComites["Classificacao"]=None
participacaoComites["PontuacaoTemp"]=0

In [ ]:
# Função que ajuda a encontrar as informações restantes

def setQtdMedalhasAtletas (row):
  infoMedalhas=pd.DataFrame(data=atletas_120[['Year', 'NOC', 'Event', 'Medal', 'Name']])
  
  infoOuroPais=infoMedalhas.loc[(infoMedalhas["Year"] ==row.AnoEdicao) & (infoMedalhas["NOC"] == row.IdComite) & (infoMedalhas["Medal"]=="Gold")]
  infoOuroPais=infoOuroPais.drop_duplicates ("Event")
  row.QtdOuro=len(infoOuroPais.index)

  infoPrataPais=infoMedalhas.loc[(infoMedalhas["Year"] ==row.AnoEdicao) & (infoMedalhas["NOC"] == row.IdComite) & (infoMedalhas["Medal"]=="Silver")]
  infoPrataPais=infoPrataPais.drop_duplicates ("Event")
  row.QtdPrata=len(infoPrataPais.index)

  infoBronzePais=infoMedalhas.loc[(infoMedalhas["Year"] ==row.AnoEdicao) & (infoMedalhas["NOC"] == row.IdComite) & (infoMedalhas["Medal"]=="Bronze")]
  infoBronzePais=infoBronzePais.drop_duplicates ("Event")
  row.QtdBronze=len(infoBronzePais.index)

  infoQtdAtletasPais=infoMedalhas.loc[(infoMedalhas["Year"] ==row.AnoEdicao) & (infoMedalhas["NOC"] == row.IdComite)]
  infoQtdAtletasPais=infoQtdAtletasPais.drop_duplicates('Name')
  row.QtdAtletas=len(infoQtdAtletasPais.index)

  row.PontuacaoTemp=10000*row.QtdOuro+100*row.QtdPrata+1*row.QtdBronze

  return row

participacaoComites= participacaoComites.apply(lambda x: setQtdMedalhasAtletas(x),axis=1)

In [ ]:
#participacaoComites=participacaoComites.loc[participacaoComites["PontuacaoTemp"] != 0]
display(participacaoComites)

      AnoEdicao IdComite  QtdAtletas  ...  QtdBronze  Classificacao  PontuacaoTemp
0          1936      AFG          15  ...          0           None              0
1          1948      AFG          25  ...          0           None              0
2          1956      AFG          12  ...          0           None              0
3          1960      AFG          12  ...          0           None              0
4          1964      AFG           8  ...          0           None              0
...         ...      ...         ...  ...        ...            ...            ...
2805       2000      ZIM          16  ...          0           None              0
2806       2004      ZIM          12  ...          1           None          10101
2807       2008      ZIM          13  ...          0           None          10300
2808       2012      ZIM           7  ...          0           None              0
2809       2016      ZIM          30  ...          0           None              0

[2810 rows x 8 columns]

In [ ]:
quadros=[]

for i in range(len(anos)):
  quadroDeUmAno = participacaoComites.loc[(participacaoComites["AnoEdicao"] == anos[i])]
  quadroDeUmAno = quadroDeUmAno.sort_values(by=['PontuacaoTemp'], ascending=False)
  quadroDeUmAno = quadroDeUmAno.reset_index(drop=True)
  quadros.append(quadroDeUmAno)

In [ ]:
def setClassificacao(quadro):
  classificacao=0
  salto=0
  pontuacao_anterior=10000000
  for i in range(len(quadro.index)):
      if quadro.at[i, 'PontuacaoTemp']<pontuacao_anterior:
        classificacao+=1+salto
        salto=0
        pontuacao_anterior=quadro.at[i, 'PontuacaoTemp']
        quadro.at[i, 'Classificacao']=classificacao
        if pontuacao_anterior==0:
          quadro.at[i, 'Classificacao']="-"
      else:
        quadro.at[i, 'Classificacao']=classificacao
        salto+=1
        if pontuacao_anterior==0:
          quadro.at[i, 'Classificacao']="-"

for j in range(len(anos)):
  setClassificacao(quadros[j])

In [ ]:
participacaoComites = pd.concat(quadros)
participacaoComites=participacaoComites.drop(columns=['PontuacaoTemp'])

In [ ]:
participacaoComites=participacaoComites.reset_index(drop=True) #Reseta os index da tabela
participacaoComites=participacaoComites.fillna("-")
participacaoComites.head(50)

    AnoEdicao IdComite  QtdAtletas  QtdOuro  QtdPrata  QtdBronze Classificacao
0        1896      USA          14       11         6          2             1
1        1896      GRE         102       10        17         17             2
2        1896      GER          19        7         5          2             3
3        1896      FRA          12        5         4          2             4
4        1896      GBR          10        3         3          3             5
5        1896      HUN           7        2         1          3             6
6        1896      AUT           3        2         1          2             7
7        1896      AUS           1        2         0          1             8
8        1896      DEN           3        1         2          3             9
9        1896      SUI           3        1         2          0            10
10       1896      ITA           1        0         0          0             -
11       1896      SWE           1        0         0          0             -
12       1900      FRA         716       28        40         34             1
13       1900      USA          75       21        16         17             2
14       1900      GBR         104       19        11         12             3
15       1900      BEL          64        6         7          5             4
16       1900      SUI          18        6         2          1             5
17       1900      GER          76        4         3          1             6
18       1900      ITA          23        3         2          0             7
19       1900      AUS           2        3         0          3             8
20       1900      DEN          13        2         3          2             9
21       1900      NED          35        1         2          4            10
22       1900      HUN          18        1         2          2            11
23       1900      CUB           1        1         1          0            12
24       1900      SWE          10        1         0          1            13
25       1900      CAN           4        1         0          1            13
26       1900      NZL           1        1         0          0            15
27       1900      LUX           1        1         0          0            15
28       1900      HAI           3        1         0          0            15
29       1900      ESP           9        1         0          0            15
30       1900      AUT          16        0         3          3            19
31       1900      NOR           7        0         2          3            20
32       1900      IND           1        0         2          0            21
33       1900      BOH           7        0         1          2            22
34       1900      COL           1        0         1          0            23
35       1900      MEX           3        0         0          1            24
36       1900      IRI           1        0         0          0             -
37       1900      GRE           3        0         0          0             -
38       1900      BRA           1        0         0          0             -
39       1900      PER           1        0         0          0             -
40       1900      ROU           1        0         0          0             -
41       1900      RUS           4        0         0          0             -
42       1900      ARG           1        0         0          0             -
43       1904      USA         524       76        79         75             1
44       1904      GER          22        4         5          7             2
45       1904      CAN          56        4         1          1             3
46       1904      CUB           3        4         0          0             4
47       1904      AUT           2        2         1          1             5
48       1904      HUN           4        2         1          1             5
49       1904      NOR           3        2         0          0             7

In [ ]:
participacaoComites.to_csv("participacaoComites.csv")

##Tabela 6 - Participação Atletas

In [ ]:
participacaoAtletas=pd.DataFrame(data=atletas_120[['Name', 'Year','Event', 'Height', 'Weight', 'Medal']])
participacaoAtletas=participacaoAtletas.rename({"Name":"IdAtleta"}, axis=1)
participacaoAtletas=participacaoAtletas.rename({"Year":"AnoEdicao"}, axis=1)
participacaoAtletas=participacaoAtletas.rename({"Event":"IdModalidade"}, axis=1)
participacaoAtletas=participacaoAtletas.rename({"Height":"Altura"}, axis=1)
participacaoAtletas=participacaoAtletas.rename({"Weight":"Peso"}, axis=1)
participacaoAtletas=participacaoAtletas.rename({"Medal":"Medalha"}, axis=1)

def setIdAtleta(row):
  nomeAtleta = row.IdAtleta
  id = atleta[atleta['Nome']==nomeAtleta].Id.values[0]
  row.IdAtleta = id
  return row

def setIdModalidade(row):
  nomeModalidade = row.IdModalidade
  id = esporteModalidade[esporteModalidade['Nome']==nomeModalidade].Id.values[0]
  row.IdModalidade = id
  return row

participacaoAtletas = participacaoAtletas.apply(lambda x: setIdAtleta(x),axis=1)  #Aplico a função acima para cada linha. ('lambda x' é tipo 'para cada linha x')
participacaoAtletas = participacaoAtletas.apply(lambda x: setIdModalidade(x),axis=1)  #Aplico a função acima para cada linha. ('lambda x' é tipo 'para cada linha x')
participacaoAtletas = participacaoAtletas.reset_index(drop=True)

KeyboardInterrupt: ignored

In [ ]:
participacaoAtletas=participacaoAtletas.reset_index(drop=True) #Reseta os index da tabela
participacaoAtletas = participacaoAtletas.fillna("-")
display(participacaoAtletas)

In [ ]:
participacaoAtletas.to_csv('participacaoAtletas.csv')

##Tabela 7 - Comitê dos Atletas

In [ ]:
comiteDosAtletas=pd.DataFrame(data=atletas_120[['NOC', 'Name']])
comiteDosAtletas=comiteDosAtletas.drop_duplicates ("Name")

comiteDosAtletas=comiteDosAtletas.rename({"Name":"IdAtleta"}, axis=1)
comiteDosAtletas=comiteDosAtletas.rename({"NOC":"IdComite"}, axis=1)

def setIdAtleta(row):
  nomeAtleta = row.IdAtleta
  id = atleta[atleta['Nome']==nomeAtleta].Id.values[0]
  row.IdAtleta = id
  return row

comiteDosAtletas = comiteDosAtletas.apply(lambda x: setIdAtleta(x),axis=1)  #Aplico a função acima para cada linha. ('lambda x' é tipo 'para cada linha x')

In [ ]:
comiteDosAtletas=comiteDosAtletas.reset_index(drop=True) #Reseta os index da tabela

comiteDosAtletas=comiteDosAtletas.fillna("-")
display(comiteDosAtletas)

       IdComite  IdAtleta
0           CHN         7
1           CHN         8
2           DEN     38234
3           DEN     25267
4           NED     19895
...         ...       ...
116117      RUS     82579
116118      ARG     30940
116119      USA     47607
116120      RUS      3284
116121      BLR     82637

[116122 rows x 2 columns]

In [ ]:
comiteDosAtletas.to_csv("comiteDosAtletas.csv")

##Tabela 8 - Esportes das Edições

In [ ]:
esportesDasEdicoes=pd.DataFrame(data=atletas_120[['Year','Event']])
esportesDasEdicoes=esportesDasEdicoes.rename({"Year":"AnoEdicao"}, axis=1)
esportesDasEdicoes=esportesDasEdicoes.drop_duplicates(['AnoEdicao', 'Event'])
esportesDasEdicoes["Ouro"] = None
esportesDasEdicoes["Prata"]=None
esportesDasEdicoes["Bronze"]=None

def setPodio(row, infoPodio):  
  try:
    infoPodioOuro=infoPodio.loc[(infoPodio["Year"] ==row.AnoEdicao) & (infoPodio["Event"] == row.Event) & (infoPodio["Medal"]=="Gold")]
    infoPodioOuro=infoPodioOuro.reset_index(drop=True)
    row.Ouro=infoPodioOuro.at[0, 'NOC'] 
  except:
    row.Ouro="-"

  try: 
    infoPodioPrata=infoPodio.loc[(infoPodio["Year"] ==row.AnoEdicao) & (infoPodio["Event"] == row.Event) & (infoPodio["Medal"]=="Silver")]
    infoPodioPrata=infoPodioPrata.reset_index(drop=True)
    row.Prata=infoPodioPrata.at[0, 'NOC']
  except:
    row.Prata="-"

  try:
    infoPodioBronze=infoPodio.loc[(infoPodio["Year"] ==row.AnoEdicao) & (infoPodio["Event"] == row.Event) & (infoPodio["Medal"]=="Bronze")]
    infoPodioBronze=infoPodioBronze.reset_index(drop=True)
    row.Bronze=infoPodioBronze.at[0, 'NOC']
  except:
    row.Bronze="-"

  return row

def setIdModalidade(row):
  nomeModalidade = row.IdModalidade
  id = esporteModalidade[esporteModalidade['Nome']==nomeModalidade].Id.values[0]
  row.IdModalidade = id
  return row

infoPodio=pd.DataFrame(data=atletas_120[['Year', 'NOC', 'Event', 'Medal']])
infoPodio=infoPodio.drop_duplicates ()
esportesDasEdicoes = esportesDasEdicoes.apply(lambda x: setPodio(x, infoPodio),axis=1)  #Aplico a função acima para cada linha. ('lambda x' é tipo 'para cada linha x')

esportesDasEdicoes=esportesDasEdicoes.rename({"Event":"IdModalidade"}, axis=1)
esportesDasEdicoes = esportesDasEdicoes.apply(lambda x: setIdModalidade(x),axis=1)  #Aplico a função acima para cada linha. ('lambda x' é tipo 'para cada linha x')

esportesDasEdicoes=esportesDasEdicoes.sort_values(by=['AnoEdicao','IdModalidade'])
esportesDasEdicoes = esportesDasEdicoes.reset_index(drop=True)

In [ ]:
esportesDasEdicoes=esportesDasEdicoes.reset_index(drop=True) #Reseta os index da tabela
esportesDasEdicoes=esportesDasEdicoes.fillna("-")
display(esportesDasEdicoes)

      AnoEdicao  IdModalidade Ouro Prata Bronze
0          1896            65  AUS   USA    FRA
1          1896            71  USA   GER    USA
2          1896            72  USA   GBR      -
3          1896            88  USA   USA    GBR
4          1896            96  AUS   HUN    GRE
...         ...           ...  ...   ...    ...
5234       2016           698  JPN   AZE    CHN
5235       2016           699  CAN   KAZ    RUS
5236       2016           700  JPN   RUS    SWE
5237       2016           701  JPN   RUS    TUN
5238       2016           702  JPN   BLR    KAZ

[5239 rows x 5 columns]

In [ ]:
esportesDasEdicoes.to_csv("esportesDasEdicoes.csv")